import pymongo
import datetime
from bson.objectid import ObjectId

conn_str = "mongodb+srv://jejomalu:123jejomalu456@cluster0.0wvicuc.mongodb.net/test"

try:

    client = pymongo.MongoClient(conn_str)

except Exception:

    print("Error:" + Exception)

#Step3

myDb = client["jejomalu"]

# print (client.list_database_names())

print(myDb.name)

# # Step 4: create a collection

myCollection = myDb["jejomalu"]
myCollection_customers = myDb["testcustomers"]

#Step 5: Create a document/ record
'''
myDoc = {

        "id_":8,

        "name":"College",

        "message":"This is pymong demo"

    }
'''
myCollection_customers.insert_many([
{ 'emailAddress' : 'rhett_fuller@gmail.com', 'firstName' : 'Rhett', 'lastName' : 'Fuller', 'billingAddress' : { 'bStreet' : '2267 184th Street', 'bUnit' : '80', 'bCity' : 'Edmonton', 'bProvince' : 'Alberta', 'bZip' : 'T5J 2R4', 'bMobileNumber' : '780-485-2704' } , 'deliveryAddress' : { 'dStreet' : '1958 Weir Crescent', 'dUnit' : '71', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M1E 3T8', 'dMobileNumber' : '647-828-4520' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Rhett Fuller', 'cardScheme' : 'Visa', 'cardLast4' : '2064', 'cardExpiryDate' : '12/2024' } },
{ 'emailAddress' : 'norah_fessenden@gmail.com', 'firstName' : 'Norah', 'lastName' : 'Fessenden', 'billingAddress' : { 'bStreet' : '1751 Wallbridge Loyalist Rd', 'bUnit' : '25', 'bCity' : 'Belleville', 'bProvince' : 'Ontario', 'bZip' : 'K8N 1L9', 'bMobileNumber' : '613-847-5941' } , 'deliveryAddress' : { 'dStreet' : '694 Yonge Street', 'dUnit' : '102', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M4W 1J7', 'dMobileNumber' : '416-963-8125' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Norah Fessenden', 'cardScheme' : 'Visa', 'cardLast4' : '2541', 'cardExpiryDate' : '06/2023' } },
{ 'emailAddress' : 'sawyer_oliver@gmail.com', 'firstName' : 'Sawyer', 'lastName' : 'Oliver', 'billingAddress' : { 'bStreet' : '2963 Pine Street', 'bUnit' : '55', 'bCity' : 'Nisku', 'bProvince' : 'Alberta', 'bZip' : 'T0C 2G0', 'bMobileNumber' : '780-955-0637' } , 'deliveryAddress' : { 'dStreet' : '674 Montreal Road', 'dUnit' : '13', 'dCity' : 'Ottawa', 'dProvince' : 'Ontario', 'dZip' : 'K1L 6C7', 'dMobileNumber' : '613-744-0751' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Sawyer Oliver', 'cardScheme' : 'Mastercard', 'cardLast4' : '5161', 'cardExpiryDate' : '03/2025' } },
{ 'emailAddress' : 'leo_clarkson@gmail.com', 'firstName' : 'Leo', 'lastName' : 'Clarkson', 'billingAddress' : { 'bStreet' : '1808 Pope St', 'bUnit' : '50', 'bCity' : 'Alberton', 'bProvince' : 'Prince Edward Island', 'bZip' : 'C0B 1K0', 'bMobileNumber' : '902-853-1818' } , 'deliveryAddress' : { 'dStreet' : '832 Nelson Street', 'dUnit' : '44', 'dCity' : 'Cat Lake', 'dProvince' : 'Ontario', 'dZip' : 'P0V 1J0', 'dMobileNumber' : '807-347-1528' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Leo Clarkson', 'cardScheme' : 'Mastercard', 'cardLast4' : '2880', 'cardExpiryDate' : '12/2026' } },
{ 'emailAddress' : 'joshua_rose@gmail.com', 'firstName' : 'Joshua', 'lastName' : 'Rose', 'billingAddress' : { 'bStreet' : '4650 rue St-Paul', 'bUnit' : '50', 'bCity' : 'Sorel', 'bProvince' : 'Quebec', 'bZip' : 'J3P 4M9', 'bMobileNumber' : '450-881-8290' } , 'deliveryAddress' : { 'dStreet' : '3818 Merton Street', 'dUnit' : '15', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M1L 3K7', 'dMobileNumber' : '416-527-3767' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Joshua Rose', 'cardScheme' : 'Visa', 'cardLast4' : '6741', 'cardExpiryDate' : '06/2025' } },
{ 'emailAddress' : 'penelope_piers@gmail.com', 'firstName' : 'Penelope', 'lastName' : 'Piers', 'billingAddress' : { 'bStreet' : '1228 A Avenue', 'bUnit' : '25', 'bCity' : 'Edmonton', 'bProvince' : 'Alberta', 'bZip' : 'T5J 0K7', 'bMobileNumber' : '780-917-8428' } , 'deliveryAddress' : { 'dStreet' : '3050 Speers Road', 'dUnit' : '86', 'dCity' : 'Oakville', 'dProvince' : 'Ontario', 'dZip' : 'L6H 3H5', 'dMobileNumber' : '905-467-2429' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Penelope Piers', 'cardScheme' : 'Visa', 'cardLast4' : '2990', 'cardExpiryDate' : '12/2025' } },
{ 'emailAddress' : 'quinn_white@gmail.com', 'firstName' : 'Quinn', 'lastName' : 'White', 'billingAddress' : { 'bStreet' : '1827 Albert Street', 'bUnit' : '131', 'bCity' : 'Kitchener', 'bProvince' : 'Ontario', 'bZip' : 'N2L 3V2', 'bMobileNumber' : '519-880-5763' } , 'deliveryAddress' : { 'dStreet' : '1827 Albert Street', 'dCity' : 'Kitchener', 'dProvince' : 'Ontario', 'dZip' : 'N2L 3V2', 'dMobileNumber' : '519-880-5763' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Quinn White', 'cardScheme' : 'Mastercard', 'cardLast4' : '6351', 'cardExpiryDate' : '01/2024' } },
{ 'emailAddress' : 'trinity_gosling@gmail.com', 'firstName' : 'Trinity', 'lastName' : 'Gosling', 'billingAddress' : { 'bStreet' : '3504 Rose Street', 'bUnit' : '73', 'bCity' : 'Regina', 'bProvince' : 'Saskatchewan', 'bZip' : 'S4P 3Y2', 'bMobileNumber' : '306-569-6952' } , 'deliveryAddress' : { 'dStreet' : '3504 Rose Street', 'dCity' : 'Regina', 'dProvince' : 'Saskatchewan', 'dZip' : 'S4P 3Y2', 'dMobileNumber' : '306-569-6952' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Trinity Gosling', 'cardScheme' : 'Mastercard', 'cardLast4' : '5230', 'cardExpiryDate' : '08/2025' } },
{ 'emailAddress' : 'hudson_davies@gmail.com', 'firstName' : 'Hudson', 'lastName' : 'Davies', 'billingAddress' : { 'bStreet' : '1364 Bridgeport Rd', 'bUnit' : '81', 'bCity' : 'Orangeville', 'bProvince' : 'Ontario', 'bZip' : 'L9W 2J9', 'bMobileNumber' : '519-215-3537' } , 'deliveryAddress' : { 'dStreet' : '1364 Bridgeport Rd', 'dCity' : 'Orangeville', 'dProvince' : 'Ontario', 'dZip' : 'L9W 2J9', 'dMobileNumber' : '519-215-3537' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Hudson Davies', 'cardScheme' : 'Visa', 'cardLast4' : '3751', 'cardExpiryDate' : '01/2024' } },
{ 'emailAddress' : 'parkamanda@gmail.com', 'firstName' : 'Amanda', 'lastName' : 'Park', 'billingAddress' : { 'bStreet' : '3610 Yonge Street', 'bUnit' : '85','bCity' : 'Toronto', 'bProvince' : 'Ontario', 'bZip' : 'M4W 1J7', 'bMobileNumber' : '416-962-6864' } , 'deliveryAddress' : { 'dStreet' : '3610 Yonge Street', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M4W 1J7', 'dMobileNumber' : '416-962-6864' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Amanda Park', 'cardScheme' : 'Visa', 'cardLast4' : '6441', 'cardExpiryDate' : '07/2026' } },
{ 'emailAddress' : 'johnsondeclan@gmail.com', 'firstName' : 'Declan', 'lastName' : 'Johnson', 'billingAddress' : { 'bStreet' : '1676 Speers Road', 'bUnit' : '90','bCity' : 'Oakville', 'bProvince' : 'Ontario', 'bZip' : 'L6J 3X4', 'bMobileNumber' : '905-815-1914' } , 'deliveryAddress' : { 'dStreet' : '1676 Speers Road', 'dCity' : 'Oakville', 'dProvince' : 'Ontario', 'dZip' : 'L6J 3X4', 'dMobileNumber' : '905-815-1914' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Declan Johnson', 'cardScheme' : 'Mastercard', 'cardLast4' : '1490', 'cardExpiryDate' : '03/2023' } },
{ 'emailAddress' : 'hillkyle@gmail.com', 'firstName' : 'Kyle', 'lastName' : 'Hill', 'billingAddress' : { 'bStreet' : '1315 St. John Street', 'bUnit' : '91', 'bCity' : 'Davidson', 'bProvince' : 'Saskatchewan', 'bZip' : 'S4P 3Y2', 'bMobileNumber' : '306-567-8680' } , 'deliveryAddress' : { 'dStreet' : '1315 St. John Street', 'dCity' : 'Davidson', 'dProvince' : 'Saskatchewan', 'dZip' : 'S4P 3Y2', 'dMobileNumber' : '306-567-8680' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Kyle Hill', 'cardScheme' : 'Mastercard', 'cardLast4' : '8030', 'cardExpiryDate' : '03/2024' } },
{ 'emailAddress' : 'evansariana@gmail.com', 'firstName' : 'Ariana', 'lastName' : 'Evans', 'billingAddress' : { 'bStreet' : '1188 St. John Street', 'bUnit' : '26','bCity' : 'Big River', 'bProvince' : 'Saskatchewan', 'bZip' : 'S4P 3Y2', 'bMobileNumber' : '306-469-8013' } , 'deliveryAddress' : { 'dStreet' : '1188 St. John Street', 'dCity' : 'Big River', 'dProvince' : 'Saskatchewan', 'dZip' : 'S4P 3Y2', 'dMobileNumber' : '306-469-8013' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Ariana Evans', 'cardScheme' : 'Visa', 'cardLast4' : '1330', 'cardExpiryDate' : '02/2024' } },
{ 'emailAddress' : 'davidscarlett@gmail.com', 'firstName' : 'Scarlett', 'lastName' : 'David', 'billingAddress' : { 'bStreet' : '1220 Tycos Dr', 'bUnit' : '29', 'bCity' : 'Toronto', 'bProvince' : 'Ontario', 'bZip' : 'M5T 1T4', 'bMobileNumber' : '416-595-0997' } , 'deliveryAddress' : { 'dStreet' : '1220 Tycos Dr', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M5T 1T4', 'dMobileNumber' : '416-595-0997' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Scarlett David', 'cardScheme' : 'Visa', 'cardLast4' : '9741', 'cardExpiryDate' : '12/2023' } },
{ 'emailAddress' : 'boyleannika@gmail.com', 'firstName' : 'Annika', 'lastName' : 'Boyle', 'billingAddress' : { 'bStreet' : '1817 Pope St', 'bUnit' : '32','bCity' : 'Alberton', 'bProvince' : 'Prince Edward Island', 'bZip' : 'C0B 1K0', 'bMobileNumber' : '902-853-7192' } , 'deliveryAddress' : { 'dStreet' : '1817 Pope St', 'dCity' : 'Alberton', 'dProvince' : 'Prince Edward Island', 'dZip' : 'C0B 1K0', 'dMobileNumber' : '902-853-7192' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Annika Boyle', 'cardScheme' : 'Mastercard', 'cardLast4' : '9290', 'cardExpiryDate' : '04/2025' } },
{ 'emailAddress' : 'currienatalie@gmail.com', 'firstName' : 'Natalie', 'lastName' : 'Currie', 'billingAddress' : { 'bStreet' : "3082 De L'Acadie Boul", 'bUnit' : '516', 'bCity' : 'Montreal', 'bProvince' : 'Quebec', 'bZip' : 'H4N 3C5', 'bMobileNumber' : '514-233-5038' } , 'deliveryAddress' : { 'dStreet' : '3567 Brand Road', 'dUnit' : '27', 'dCity' : 'Saskatoon', 'dProvince' : 'Saskatchewan', 'dZip' : 'S7K 1W8', 'dMobileNumber' : '306-717-8298' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Natalie Currie', 'cardScheme' : 'Mastercard', 'cardLast4' : '9830', 'cardExpiryDate' : '01/2023' } },
{ 'emailAddress' : 'altmancharlotte@gmail.com', 'firstName' : 'Charlotte', 'lastName' : 'Altman', 'billingAddress' : { 'bStreet' : '4854 Tycos Dr', 'bUnit' : '117', 'bCity' : 'Toronto', 'bProvince' : 'Ontario', 'bZip' : 'M5T 1T4', 'bMobileNumber' : '416-343-8934' } , 'deliveryAddress' : { 'dStreet' : '4554 chemin Georges', 'dUnit' : '108', 'dCity' : 'St Felix De Valois', 'dProvince' : 'Quebec', 'dZip' : 'J0K 2M0', 'dMobileNumber' : '450-889-2867' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Charlotte Altman', 'cardScheme' : 'Visa', 'cardLast4' : '6745', 'cardExpiryDate' : '03/2023' } },
{ 'emailAddress' : 'olsonbrielle@gmail.com', 'firstName' : 'Brielle', 'lastName' : 'Olson', 'billingAddress' : { 'bStreet' : '625 40th Street', 'bUnit' : '218', 'bCity' : 'Calgary', 'bProvince' : 'Alberta', 'bZip' : 'T2N 2A7', 'bMobileNumber' : '403-283-1490' } , 'deliveryAddress' : { 'dStreet' : '2665 rue Parc', 'dUnit' : '19', 'dCity' : 'St Cyrille De Wendover', 'dProvince' : 'Quebec', 'dZip' : 'J1Z 1E1', 'dMobileNumber' : '819-397-4174' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Brielle Olson', 'cardScheme' : 'Visa', 'cardLast4' : '7481', 'cardExpiryDate' : '11/2023' } },
{ 'emailAddress' : 'mccoycharlie@gmail.com', 'firstName' : 'Charlie', 'lastName' : 'McCoy', 'billingAddress' : { 'bStreet' : '1266 rue Ontario Ouest', 'bUnit' : '319', 'bCity' : 'Montreal', 'bProvince' : 'Quebec', 'bZip' : 'H2X 1Y8', 'bMobileNumber' : '514-982-1624' } , 'deliveryAddress' : { 'dStreet' : '1165 Duke Street', 'dUnit' : '110', 'dCity' : 'Montreal', 'dProvince' : 'Quebec', 'dZip' : 'H3C 5K4', 'dMobileNumber' : '514-229-9713' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Charlie McCoy', 'cardScheme' : 'Mastercard', 'cardLast4' : '1351', 'cardExpiryDate' : '10/2026' } },
{ 'emailAddress' : 'hennessyadelaide@gmail.com', 'firstName' : 'Adelaide', 'lastName' : 'Hennessy', 'billingAddress' : { 'bStreet' : '2172 Stoney Creek', 'bUnit' : '310', 'bCity' : 'Green Lake', 'bProvince' : 'Saskatchewan', 'bZip' : 'S4P 3Y2', 'bMobileNumber' : '306-832-9394' } , 'deliveryAddress' : { 'dStreet' : '3238 102nd Avenue', 'dUnit' : '411', 'dCity' : 'Fort St John', 'dProvince' : 'British Columbia', 'dZip' : 'V1J 3Y7', 'dMobileNumber' : '250-263-5582' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Adelaide Hennessy', 'cardScheme' : 'Mastercard', 'cardLast4' : '8225', 'cardExpiryDate' : '05/2026' } },
{ 'emailAddress' : 'jessewilliams@gmail.com', 'firstName' : 'Jesse', 'lastName' : 'Williams', 'billingAddress' : { 'bStreet' : '564 Heritage Drive', 'bUnit' : '311', 'bCity' : 'Calgary', 'bProvince' : 'Alberta', 'bZip' : 'T2V 2W2', 'bMobileNumber' : '403-875-0334' } , 'deliveryAddress' : { 'dStreet' : '4681 Baker Street', 'dUnit' : '312', 'dCity' : 'London', 'dProvince' : 'Ontario', 'dZip' : 'N0N 0N0', 'dMobileNumber' : '519-858-8035' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Jesse Williams', 'cardScheme' : 'Visa', 'cardLast4' : '3551', 'cardExpiryDate' : '04/2026' } },
{ 'emailAddress' : 'ivyclarkson@gmail.com', 'firstName' : 'Ivy', 'lastName' : 'Clarkson', 'billingAddress' : { 'bStreet' : '1028 Garafraxa St', 'bUnit' : '312', 'bCity' : 'Tara', 'bProvince' : 'Ontario', 'bZip' : 'N0H 2N0', 'bMobileNumber' : '519-934-6315' } , 'deliveryAddress' : { 'dStreet' : '1028 Garafraxa St', 'dUnit' : '312', 'dCity' : 'Tara', 'dProvince' : 'Ontario', 'dZip' : 'N0H 2N0', 'dMobileNumber' : '519-934-6315' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Ivy Clarkson', 'cardScheme' : 'Visa', 'cardLast4' : '1551', 'cardExpiryDate' : '09/2023' } },
{ 'emailAddress' : 'bethanynevin@gmail.com', 'firstName' : 'Bethany', 'lastName' : 'Nevin', 'billingAddress' : { 'bStreet' : '3816 Hardy Street', 'bUnit' : '313', 'bCity' : 'Kelowna', 'bProvince' : 'British Columbia', 'bZip' : 'V1Y 8H2', 'bMobileNumber' : '250-712-4772' } , 'deliveryAddress' : { 'dStreet' : '3816 Hardy Street', 'dUnit' : '313', 'dCity' : 'Kelowna', 'dProvince' : 'British Columbia', 'dZip' : 'V1Y 8H2', 'dMobileNumber' : '250-712-4772' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Bethany Nevin', 'cardScheme' : 'Mastercard', 'cardLast4' : '7225', 'cardExpiryDate' : '09/2023' } },
{ 'emailAddress' : 'octaviaboyd@gmail.com', 'firstName' : 'Octavia', 'lastName' : 'Boyd', 'billingAddress' : { 'bStreet' : '2179 Côte Joyeuse', 'bUnit' : '314', 'bCity' : "L'etape", 'bProvince' : 'Quebec', 'bZip' : 'H0H 0H0', 'bMobileNumber' : '418-859-5959' } , 'deliveryAddress' : { 'dStreet' : '2179 Côte Joyeuse', 'dUnit' : '314', 'dCity' : "L'etape", 'dProvince' : 'Quebec', 'dZip' : 'H0H 0H0', 'dMobileNumber' : '418-859-5959' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Octavia Boyd', 'cardScheme' : 'Mastercard', 'cardLast4' : '5941', 'cardExpiryDate' : '05/2026' } },
{ 'emailAddress' : 'anastasiatimbrell@gmail.com', 'firstName' : 'Anastasia', 'lastName' : 'Timbrell', 'billingAddress' : { 'bStreet' : '454 Merivale Road', 'bUnit' : '215', 'bCity' : 'Ottawa', 'bProvince' : 'Ontario', 'bZip' : 'K2H 5B6', 'bMobileNumber' : '613-721-0698' } , 'deliveryAddress' : { 'dStreet' : '454 Merivale Road', 'dUnit' : '215', 'dCity' : 'Ottawa', 'dProvince' : 'Ontario', 'dZip' : 'K2H 5B6', 'dMobileNumber' : '613-721-0698' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Anastasia Timbrell', 'cardScheme' : 'Visa', 'cardLast4' : '9861', 'cardExpiryDate' : '03/2024' } },
{ 'emailAddress' : 'donovanmarkle@gmail.com', 'firstName' : 'Donovan', 'lastName' : 'Markle', 'billingAddress' : { 'bStreet' : '4337 Algonquin Blvd', 'bUnit' : '216', 'bCity' : 'Timmins', 'bProvince' : 'Ontario', 'bZip' : 'P4N 7C4', 'bMobileNumber' : '705-668-1540' } , 'deliveryAddress' : { 'dStreet' : '4337 Algonquin Blvd', 'dUnit' : '216', 'dCity' : 'Timmins', 'dProvince' : 'Ontario', 'dZip' : 'P4N 7C4', 'dMobileNumber' : '705-668-1540' } , 'paymentMethod' : { 'paymentType' : 'Credit', 'nameOnCard' : 'Donovan Markle', 'cardScheme' : 'Visa', 'cardLast4' : '4070', 'cardExpiryDate' : '12/2023' } },
{ 'emailAddress' : 'sloanmclaughlin@gmail.com', 'firstName' : 'Sloan', 'lastName' : 'McLaughlin', 'billingAddress' : { 'bStreet' : '3729 Northumberland Street', 'bUnit' : '117', 'bCity' : 'Hillsburgh', 'bProvince' : 'Ontario', 'bZip' : 'N0B 1Z0', 'bMobileNumber' : '519-855-4411' } , 'deliveryAddress' : { 'dStreet' : '3729 Northumberland Street', 'dUnit' : '117', 'dCity' : 'Hillsburgh', 'dProvince' : 'Ontario', 'dZip' : 'N0B 1Z0', 'dMobileNumber' : '519-855-4411' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Sloan McLaughlin', 'cardScheme' : 'Mastercard', 'cardLast4' : '1151', 'cardExpiryDate' : '08/2024' } },
{ 'emailAddress' : 'saraholiver@gmail.com', 'firstName' : 'Sarah', 'lastName' : 'Oliver', 'billingAddress' : { 'bStreet' : '3908 René-Lévesque Blvd', 'bUnit' : '218', 'bCity' : 'Montreal', 'bProvince' : 'Quebec', 'bZip' : 'H3B 4W8', 'bMobileNumber' : '514-573-0262' } , 'deliveryAddress' : { 'dStreet' : '3908 René-Lévesque Blvd', 'dUnit' : '218', 'dCity' : 'Montreal', 'dProvince' : 'Quebec', 'dZip' : 'H3B 4W8', 'dMobileNumber' : '514-573-0262' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Sarah Oliver', 'cardScheme' : 'Mastercard', 'cardLast4' : '6251', 'cardExpiryDate' : '10/2024' } },
{ 'emailAddress' : 'serenareeves@gmail.com', 'firstName' : 'Serena', 'lastName' : 'Reeves', 'billingAddress' : { 'bStreet' : '3610 Bloor Street', 'bUnit' : '219', 'bCity' : 'Vegreville', 'bProvince' : 'Alberta', 'bZip' : 'T0B 4L0', 'bMobileNumber' : '780-632-2540' } , 'deliveryAddress' : { 'dStreet' : '3610 Bloor Street', 'dUnit' : '219', 'dCity' : 'Vegreville', 'dProvince' : 'Alberta', 'dZip' : 'T0B 4L0', 'dMobileNumber' : '780-632-2540' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Serena Reeves', 'cardScheme' : 'Visa', 'cardLast4' : '4078', 'cardExpiryDate' : '08/2023' } },
{ 'emailAddress' : 'kalebbanks@gmail.com', 'firstName' : 'Kaleb', 'lastName' : 'Banks', 'billingAddress' : { 'bStreet' : '3371 Woolwick Drive', 'bUnit' : '320', 'bCity' : 'Toronto', 'bProvince' : 'Ontario', 'bZip' : 'M1H 1A8', 'bMobileNumber' : '416-438-7286' } , 'deliveryAddress' : { 'dStreet' : '3371 Woolwick Drive', 'dUnit' : '320', 'dCity' : 'Toronto', 'dProvince' : 'Ontario', 'dZip' : 'M1H 1A8', 'dMobileNumber' : '416-438-7286' } , 'paymentMethod' : { 'paymentType' : 'Debit', 'nameOnCard' : 'Kaleb Banks', 'cardScheme' : 'Visa', 'cardLast4' : '8641', 'cardExpiryDate' : '11/2023' } }
]);
